# Generated by Django 3.2.7 on 2021-12-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alignment', models.CharField(blank=True, choices=[('Lawful Good', 'Lg'), ('Neutral Good', 'Ng'), ('Chaotic Good', 'Cg'), ('Lawful Neutral', 'Ln'), ('Neutral', 'Nn'), ('Chaotic Neutral', 'Cn'), ('Lawful Evil', 'Le'), ('Neutral Evil', 'Ne')], max_length=100, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='character_api.role')),
            ],
            options={
                'db_table': 'character',
                'managed': True,
            },
        ),
    ]
